function Data = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   UNTITLED = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   UNTITLED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Untitled = importfile('18070901.CSV', 19, 19);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/07/31 11:05:10

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 19;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using the
% specified date format.
try
    dates{1} = datetime(dataArray{1}, 'Format', 'dd/MM/yy HH:mm:ss', 'InputFormat', 'dd/MM/yy HH:mm:ss');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{1} = cellfun(@(x) x(2:end-1), dataArray{1}, 'UniformOutput', false);
        dates{1} = datetime(dataArray{1}, 'Format', 'dd/MM/yy HH:mm:ss', 'InputFormat', 'dd/MM/yy HH:mm:ss');
    catch
        dates{1} = repmat(datetime([NaN NaN NaN]), size(dataArray{1}));
    end
end

dates = dates(:,1);

%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Data = table;
Data.DateTime = dates{:, 1};
Data.Bin00 = cell2mat(rawNumericColumns(:, 1));
Data.Bin01 = cell2mat(rawNumericColumns(:, 2));
Data.Bin02 = cell2mat(rawNumericColumns(:, 3));
Data.Bin03 = cell2mat(rawNumericColumns(:, 4));
Data.Bin04 = cell2mat(rawNumericColumns(:, 5));
Data.Bin05 = cell2mat(rawNumericColumns(:, 6));
Data.Bin06 = cell2mat(rawNumericColumns(:, 7));
Data.Bin07 = cell2mat(rawNumericColumns(:, 8));
Data.Bin08 = cell2mat(rawNumericColumns(:, 9));
Data.Bin09 = cell2mat(rawNumericColumns(:, 10));
Data.Bin10 = cell2mat(rawNumericColumns(:, 11));
Data.Bin11 = cell2mat(rawNumericColumns(:, 12));
Data.Bin12 = cell2mat(rawNumericColumns(:, 13));
Data.Bin13 = cell2mat(rawNumericColumns(:, 14));
Data.Bin14 = cell2mat(rawNumericColumns(:, 15));
Data.Bin15 = cell2mat(rawNumericColumns(:, 16));
Data.MToFBin1us = cell2mat(rawNumericColumns(:, 17));
Data.MToFBin3 = cell2mat(rawNumericColumns(:, 18));
Data.MToFBin5 = cell2mat(rawNumericColumns(:, 19));
Data.MToFBin7 = cell2mat(rawNumericColumns(:, 20));
Data.SamplingPeriods = cell2mat(rawNumericColumns(:, 21));
Data.SFRmls = cell2mat(rawNumericColumns(:, 22));
Data.Checksum = cell2mat(rawNumericColumns(:, 23));
Data.PMr = cell2mat(rawNumericColumns(:, 24));
Data.AvgLongValue = cell2mat(rawNumericColumns(:, 25));
Data.AvgShortValue = cell2mat(rawNumericColumns(:, 26));
Data.LiveUnits = cell2mat(rawNumericColumns(:, 27));
Data.AvgShortUnits = cell2mat(rawNumericColumns(:, 28));
Data.AvgLongUnits = cell2mat(rawNumericColumns(:, 29));
Data.LogRates = cell2mat(rawNumericColumns(:, 30));
Data.Channel_1 = cell2mat(rawNumericColumns(:, 31));
Data.Channel_2 = cell2mat(rawNumericColumns(:, 32));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Untitled.DateTime=datenum(Untitled.DateTime);

